# Generated by Django 4.2.3 on 2024-02-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
