# Generated by Django 4.2.3 on 2024-02-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_admin', '0006_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(null=True, upload_to='blogs/'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogs',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='websitedata',
            name='image',
            field=models.ImageField(null=True, upload_to='pages/'),
        ),
        migrations.AddField(
            model_name='websitedata',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='subcategory'),
        ),
    ]
